name: CI

on:
  pull_request:
    types:
      - ready_for_review
      - reopened
      - opened
      - synchronize
    branches:
      - main
  push:
    branches:
      - main

  # manual trigger from Github UI - Action tab
  workflow_dispatch:

env:
  NEXT_PUBLIC_INFURA_NETWORK: mainnet

jobs:
  run-yarn-tests:
    name: Run yarn tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
  
      - name: Install packages
        run: yarn install

      - name: Tests with yarn
        run: yarn test

  lint-translations:
    name: Lint source code for missing translations.
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
  
      - name: Install packages
        run: yarn install

      - name: Lint translations
        run: 'yarn i18n:lint'

  next-build:
    name: Build NextJS app.
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
  
      - name: Install packages
        run: yarn install

      - name: Build NextJS app
        run: 'yarn build'

  